server:
  port: 8089

spring:
  application:
    name: event-manager

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:postgresql://localhost:5438/event_manager
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health, prometheus

logging:
  level:
    root: INFO
    org.springframework.web: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

jwt:
  secret: "74cf29aeb2a65032d8e3c252883040648054f42905d3f2ad80e9dfce24d36c1b"
  expiration: 86400000